FROM openjdk:18-alpine
MAINTAINER onuryaldir


COPY Task/target/Task-0.0.1-SNAPSHOT.jar /Task-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/Task-0.0.1-SNAPSHOT.jar"]

#ENTRYPOINT ["java","-jar","/ApiController-0.0.1-SNAPSHOT.jar"]



