CREATE USER onuryaldir WITH ENCRYPTED PASSWORD 'password';

CREATE DATABASE "Group";
GRANT ALL PRIVILEGES ON DATABASE "Group" TO onuryaldir;

CREATE DATABASE "User";
GRANT ALL PRIVILEGES ON DATABASE "User" TO onuryaldir;

CREATE DATABASE "Task";
GRANT ALL PRIVILEGES ON DATABASE Task TO onuryaldir;